name: Python Dash CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dash pandas gunicorn black flake8

    - name: Code Formatting with Black
      run: |
        black --check .

    - name: Lint with flake8
      run: |
        flake8 .

        #    - name: Run tests
        #      run: |
        #        # Add commands to run your tests here.
        #
        #    - name: Deploy
        #      if: github.ref == 'refs/heads/main'
        #      run: |
        #        # Add commands to deploy your dashboard here.

